#!/bin/bash

set -uo pipefail
IFS=$'\n\t'

targets=(
	appcache
	iconcache
	spotlight
	preferences
)

function usage {
	printf "\nUsage: rebuild all"
	for t in ${targets[*]}; do
		printf "|$t"
	done
	printf "\n       rebuild help\n"
	exit $*
}

if [[ $# -eq 0 ]]; then
	>&2 echo "rebuild: target missing"
	usage 1
fi

for t in $*; do
	case $t in
		(all)
			$0 ${targets[*]}
			;;
		(iconcache)
			rm -rf /Library/Caches/com.apple.iconservices.store
			;;
		(appcache)
			sudo /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
				-kill -r -f -v -all s,l,u
			sudo /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
				-seed -r -f -v
			;;
		(spotlight)
			mdutil -E -i on /
			;;
		(preferences)
			killall -u "$USER" cfprefsd
			;;
		(help|--help)
			echo "The rebuild utility provides a simple interface to rebuild caches and databases."
			usage
			;;
		(*)
			alt=($(which -a rebuild))
			if [[ ${#alt[@]} -gt 1 ]]; then
				${alt[1]} "$@"
			else
				>&2 echo "Unknown target: $t"
				usage 1
			fi
	esac
done
